#!/bin/bash

####################################
# argument

infile=${1:-"-"}

####################################
# Main

{
    echo "ibase=2;obase=10000;"

    cat $infile		|
	tr -Cd '01'	|
	fold -w 4	|
	awk '{ printf("%04d\n", $0) }'
}		|
    bc -ql	|
    {
	tr -d '\n'	|
	    fold -w 2
	echo
    }

####################################
exit 0
