#!/bin/bash

####################################
# argument

infile=${1:-"-"}

####################################
# Main

{
    echo "ibase=16;obase=2;"

    grep -Eo '[0-9A-Za-z]' "$infile"	|
	tr 'a-z' 'A-Z'
}				|
    bc -ql			|
    {
	awk '{ printf("%04d",$0) }'	|
	    fold -w 8
	echo
    }

####################################
exit 0
